### ISSUE TITLE
Entity Tick Crash

### ISSUE THREAD

**Issue by thecuz1** [hlysine/create_power_loader#22] opened 2024-05-11 05:33 UTC
Forwarded from [create](https://github.com/Creators-of-Create/Create/issues/6454) issue

Dedicated server crashed upon start due to ticking entity inside the range of a power loader

https://mclo.gs/Gtt2Kod - https://pastebin.com/KhSz8F5E

Removing power loader allowed the server to start normally, the only mod removed, reliably reproducing the error seems to depend on the size of the world/server performance and not the amount of mods present

**Comment by hlysine** [comment] 2024-05-11 08:42
I don't think the issue is specific to Power Loader after reading your logs. Please try out the following to help find the root cause:

1. Keep all your other mods but remove Power Loader, then use `/forceload` command to load the chunks that would normally be loaded by Power Loader. Try reproducing this crash again with the same setup.
2. Use `F3+G` to visualize the chunk borders and check if the threshold switch is next to one. Move the whole setup to another place and try reproducing the crash again.
3. Try to reproduce the crash with all unrelated mods removed, or narrow it down to a small list that still causes the crash.

**Comment by thecuz1** [comment] 2024-05-19 13:28
Reproducing this outside the original server doesn't seem possible even with the same map and OS + java version, unfortunately testing on the original one isn't possible, solved using a custom version of create for now, the threshhold switch was attached to a 2 wide item vault below it with it all being in one chunk covered by the loader 
![2024-05-19_10 50 50](https://github.com/hlysine/create_power_loader/assets/68039262/6d1b0f28-be0e-43a3-9122-c13c2a045140) hope this help narrow it down in some way

**Comment by hlysine** [comment] 2024-05-19 14:06
In that case, I really don't think the problem is related to Power Loader. Power Loader only loads the chunk on server start, which allows the problem to manifest early. I'm going to close this for now. If you come across this problem consistently in the future, please open a new issue with steps to reproduce the crash.

**Closed by hlysine** 2024-05-19 14:06 UTC
Labels: bug, need info, level: crash, type: compat
