### ISSUE TITLE
Crash on Launch with Fabric 1.20.1

### ISSUE THREAD

**Issue by HB-Stratos** [hlysine/create_power_loader#10] opened 2024-02-21 16:58 UTC
As I said in the title, I tried to use the new fabric version for my modpack, but installing the mod makes the game crash while loading. 

Here's the log on mclo.gs: https://mclo.gs/1KpZXan

Here's the log in a more permanent way: [1KpZXan.txt](https://github.com/hlysine/create_power_loader/files/14362613/1KpZXan.txt)

Error Snippet (from log):
```
[17:48:54] [Render thread/ERROR]: Mixin apply for mod create_power_loader failed create_power_loader.mixins.json:GlobalRailwayManagerMixin from mod create_power_loader
```

Minecraft version:
1.20.1
Fabric loader version:
0.15.6
Power loader version: 
1.4.0

Thanks in Advance for help!

**Comment by hlysine** [comment] 2024-02-22 11:08
Thanks for the detailed report. It's caused by mixin remapping issues and is fixed in 1.4.1-fabric

**Closed by hlysine** 2024-02-22 11:08 UTC
Labels: bug, duplicate, level: crash, type: mixin
